FSxBucketName as optional parameter
aws-samples/aws-genomics-workflows pull request #210
Opened 2022-08-29 09:20 UTC by henriqueribeiro

*Description of changes:*
Make `FSxBucketName` an optional parameter

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-29 13:35 UTC, markjschreiber requested changes
Possibly, a better way to make a variable optional is to use `Fn::If` and `AWS::NoValue`. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

For example https://cloudonaut.io/optional-parameter-in-cloudformation/

2022-08-30 11:55 UTC, henriqueribeiro commented
@markjschreiber not sure if this is what you had in mind

2022-08-30 13:26 UTC, markjschreiber approved these changes

2022-09-01 12:52 UTC, henriqueribeiro commented
ping to keep it alive :smile:

2022-09-01 16:26 UTC, merged